import logging
import time
import os
import sys
import numpy as np
import torch

from utils_2d.plots2d import plot_mesh
from utils_2d.loss_plot import plot_loss
from utils_2d.fcn2d import FCN2D
from utils_2d.gen_plot2d import generate_gif
from utils_2d.gen_data2d import data_gen
from utils_2d.utils2d import create_tests_folder
from pydoe import lhs

torch.set_default_dtype(torch.float)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

if device == 'cuda':
    print(torch.cuda.get_device_name())

steps = 5000
batch_size = 1000
w_bc = 100
w_pde = 1
lr = 1e-4
layers = np.array([3,50,50,50,50,1])
log_freq = 50

case = "example_2"
if case == 'example_1':
    domain = [-1,1,-1,1,0,1]
elif case == 'example_2':
    domain = [0,1,0,1,0,10]

N_test_x = 100
N_test_y = 100
N_test_t = 100
N_train_x = 50
N_train_y = 50
N_train_t = 50
N_bc = 1000

result_fol = create_tests_folder(parent_folder = 'results_2d', prefix = f"_{case}")
if not os.path.exists(result_fol):
    os.makedirs(result_fol)
logging.basicConfig(handlers = [logging.StreamHandler(sys.stdout), logging.FileHandler(result_fol + "/0_log.txt")], level = logging.INFO, format = "%(message)s")
logger = logging.getLogger()

# Create Data

# This data generated by CPU.
DG = data_gen(domain, case)
x_trainPDE = DG.get_PDE_dataset(N_train_x, N_train_y, N_train_t)
x_trainBC, u_trainBC = DG.get_BC_dataset(N_bc)
u_real, x_test, u_test, X, Y, T = DG.get_test_dataset(N_test_x, N_test_y, N_test_t)

# If the device is CUDA (or CUDA is installed), the data are sent to GPU
X_train_bc = x_trainBC.float().to(device)
U_train_bc = u_trainBC.float().to(device)
X_train_pde = x_trainPDE.float().to(device)
X_test = x_test.float().to(device)
U_test = u_test.float().to(device)


# Create model and optimizer
PINN = FCN2D(layers, case, domain)
PINN.to(device)
print(PINN) # testing
optimizer = torch.optim.Adam(PINN.parameters(), lr = lr, amsgrad = False)

res_dict = {'loss':[], 'loss_bc':[], 'loss_pde':[], 'rela_err_l2':[], 'iteration':[]} # menambahkan lossPDE kedalam kamus res_dict
start_time_a = time.time()
count = 1
#target_time = 0.01 # choose time t between the domain
#time_index = torch.argmin(torch.abs(T[0,:] - target_time)).item() # it will show the column order index within the tensor
plot_mesh(X, Y, T, u_real, case, name = f"real_function", folder = result_fol, time_idx = 0)

for i in range(1, steps + 1):
    idx = np.random.choice(X_train_pde.shape[0], batch_size, replace = False)
    loss = PINN.loss(X_train_bc, U_train_bc, X_train_pde[idx, :], w_bc = w_bc, w_pde = w_pde)
    #loss_pde = PINN.lossPDE(X_train_pde[idx, :])
    loss_bc = w_bc * PINN.lossbc(X_train_bc, U_train_bc)
    loss_pde = loss - loss_bc
    optimizer.zero_grad()
    loss.backward()
    #loss_pde.backward()
    loss_bc.backward()
    optimizer.step()

    # do not forget to append the dictionary
    res_dict['iteration'].append(i)
    res_dict['loss'].append(loss.item())
    res_dict['loss_pde'].append(loss_pde.item())
    res_dict['loss_bc'].append(loss_bc.item())
    
    with torch.no_grad():
        err_l2_mean, error = PINN.error_l2_norm(X_test, U_test)
        res_dict['rela_err_l2'].append(err_l2_mean.item())
    if i % log_freq == 0 or i == 1:
        u_predict = PINN(X_test)
        arr_y1 = u_predict.reshape(shape = [N_test_t, N_test_x, N_test_y]).permute(1,2,0).detach().cpu()
        plot_mesh(X, Y, T, arr_y1, case, name = f"approx_{count}", loss = loss.item(), folder = result_fol, iter = i, time_idx = 0)
        if i % (log_freq*2)==0 or i == 1:
            logger.info(f"| Iter: {i} | Loss: {loss.item():.4f} | Loss Res: {loss_pde.item():.4f} | Total_time: {(time.time() - start_time_a)/60:.1f} minutes")
        count += 1

print('Training Finished')
generate_gif(result_fol, count, remove_imgs = True)
#plot_loss(res_dict['iteration'], res_dict['loss'], T, 'Total Loss', 'just_example', case = case, time_idx = 0)
plot_loss(res_dict['iteration'], res_dict['loss'], T, 'LossScores_vs_iteration2d', case = case, losspde = None, lossbc =None , time_idx = 0)
